# Site settings
title: "Outiller CAFDO" 
email: hello@ogptoolbox.fr
url: https://cecilaki.github.io/
description: "Presentation du projet Outiller CAFDO"
skills: "Outiller"
meta_author: Lesbians Who Tech Paris 

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: EEEEEE #d8b365
  primary-rgb: "39, 196, 244" #"216,179,101"
  secondary: 293A6B #0A070C #B2230B
  secondary-dark: 87BDEE #26BDEA #F62459 #01665e

# Footer settings
footer:
  copyright: CC-BY
  location: Location
  social: Contact
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ogptoolbox
  - title: mail
    url: mailto:cecile@datactivi.st


# Postal address (add as many lines as necessary)
address:
  - line: OGP Toolbox
  - line: Paris

# Credits content
credits: 'OGP Toolbox & Ecole des Donnees'

# Build settings
markdown: kramdown
permalink: pretty
